name: ChatBuilderLib
main: io.github.yannici.chatbuilderlib.Builder
version: 1.0.2
depend: []
softdepend: []
commands:
    cbl:
        description: Test of the lib
        usage: /<command>
        permission: op